name: Deploy React Application

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Source
        uses: actions/checkout@v4
      - name: Login to docker hub
        run: docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
      - name: Build Docker Image with secret
        run: docker build -t noufalkv/tradingr-chart --build-arg REACT_APP_NODE_ENV='production' --build-arg REACT_APP_SERVER_BASE_URL='${{ secrets.REACT_APP_SERVER_BASE_URL }}'  .
      - name: Publish Image to docker hub
        run: docker push noufalkv/tradingr-chart:latest

  deploy:
    needs: build
    runs-on: self-hosted
    steps:
      - name: Pull image from docker hub
        run: docker pull noufalkv/tradingr-chart:latest
      - name: Delete old container
        run: docker rm -f reactjs-app-container || true
      - name: Run Docker Container
        run: docker run -d -p 3000:80 --name reactjs-app-container noufalkv/tradingr-chart:latest
